import styles from '../styles/Home.module.css'
import Head from 'next/head'
import Banner from "@/components/banner/Banner";
import Image from "next/image";
import Card from "@/components/card/Card";
import {fetchCoffeeShops} from "../../utils/foursquare-utils";
import FindGeoLocation from "../../utils/geoLocation";


/**
 * This function is used to fetch the coffee shops from the Foursquare API and pre-render the page
 * @returns {Promise<{props: {coffeeShops: {}}}>}
 */
export const getStaticProps = async () => {
    const coffeeShops = await fetchCoffeeShops();

    return {
        props: {
            coffeeShops: coffeeShops
        }
    };
};


const Home = (staticProps) => {
    const {coffeeShops} = staticProps;
    const {getUsersLocation, latLong, locationErrorMsg, locatingUser} = FindGeoLocation();


    const onViewLocalStoresButtonClick = () => {
        getUsersLocation();
    }
    console.log(latLong)


    // *************************** JSX *************************** //
    return (
        <>
            <Head>
                <title>Coffee Connoisseur</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <main className={styles.main}>
                <Banner
                    buttonText={locatingUser ? 'Finding your location' : 'View your local coffee shops'}
                    onClickHandler={onViewLocalStoresButtonClick}
                />

                {/*logic to display the location error message*/}
                {
                    locationErrorMsg && (
                        <p>Error: {locationErrorMsg}</p>
                    )
                }
                {/*end of logic to display the location error message*/}

                <Image src='/static/hero-image.png' alt='hero image' width={700} height={400}/>

                {/*logic displaying if there are coffee shops in DENVER*/}
                {
                    coffeeShops.length > 0 && (
                        <div className={styles.sectionWrapper}>
                            <h2 className={styles.heading2}>Denver Coffee Shops</h2>
                            <div className={styles.cardLayout}>
                                {/*mapping over the coffee shops*/}
                                {
                                    coffeeShops.map(coffeeShop => {
                                        const {id, name, imgUrl} = coffeeShop;
                                        return (
                                            <Card
                                                key={id}
                                                name={name}
                                                href={`/coffee-store/${id}`}
                                                imgUrl={imgUrl ? imgUrl : '/static/generic-coffee.jpg'}
                                            />
                                        );
                                    })
                                }
                                {/*end of coffee shops mapping*/}
                            </div>
                        </div>
                    )
                }
                {/*end of logic displaying if there are coffee shops*/}
            </main>
        </>
    )
}


export default Home