import styles from '../styles/Home.module.css'
import Head from 'next/head'
import Banner from "@/components/banner/Banner";
import Image from "next/image";


const Home = () => {

    // *************************** FUNCTIONS *************************** //
    const onBannerButtonClick = () => {
        console.log('Banner button clicked');
    }


    // *************************** JSX *************************** //
    return (
        <>
            <Head>
                <title>Coffee Connoisseur</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <main className={styles.main}>
                <Banner buttonText='View your local coffee shops' onClickHandler={onBannerButtonClick}/>
                <Image src='/static/hero-image.png' alt='hero image' width={700} height={400}/>
            </main>
        </>
    )
}


export default Home